import type { TouristSpot, Accommodation } from "@/types";

export const sampleSpots: TouristSpot[] = [
  {
    id: "1",
    name: "Aliwagwag Falls",
    description: "Stunning cascading waterfalls with 84 tiers",
    location: "Cateel, Davao Oriental",
    category: "waterfall",
    budgetLevel: "budget",
    estimatedCost: 500,
    bestTimeToVisit: "June - November",
  },
  {
    id: "2",
    name: "Pujada Bay",
    description: "Pristine bay with white sand beaches",
    location: "Mati City, Davao Oriental",
    category: "beach",
    budgetLevel: "moderate",
    estimatedCost: 800,
    bestTimeToVisit: "March - May",
  },
  {
    id: "3",
    name: "Sleeping Dinosaur",
    description: "Unique mountain formation resembling a sleeping dinosaur",
    location: "Mati City, Davao Oriental",
    category: "nature",
    budgetLevel: "budget",
    estimatedCost: 300,
    bestTimeToVisit: "Year-round",
  },
  {
    id: "4",
    name: "Dahican Beach",
    description: "Famous for surfing and skimboarding",
    location: "Mati City, Davao Oriental",
    category: "beach",
    budgetLevel: "moderate",
    estimatedCost: 600,
    bestTimeToVisit: "October - April",
  },
  {
    id: "5",
    name: "Cape San Agustin",
    description: "Historic lighthouse with panoramic views",
    location: "Governor Generoso, Davao Oriental",
    category: "historical",
    budgetLevel: "moderate",
    estimatedCost: 800,
    bestTimeToVisit: "Year-round",
  },
];

export const sampleAccommodations: Accommodation[] = [
  {
    id: "1",
    name: "Mati Bay Resort",
    type: "resort",
    location: "Mati City",
    pricePerNight: 2500,
    budgetLevel: "moderate",
    amenities: ["WiFi", "Pool", "Restaurant"],
  },
  {
    id: "2",
    name: "Beachside Homestay",
    type: "homestay",
    location: "Dahican",
    pricePerNight: 800,
    budgetLevel: "budget",
    amenities: ["WiFi", "Breakfast"],
  },
  {
    id: "3",
    name: "Cateel Inn",
    type: "inn",
    location: "Cateel",
    pricePerNight: 1200,
    budgetLevel: "budget",
    amenities: ["WiFi", "Parking"],
  },
  {
    id: "4",
    name: "Luxury Beach Resort",
    type: "resort",
    location: "Pujada Bay",
    pricePerNight: 5000,
    budgetLevel: "luxury",
    amenities: ["WiFi", "Pool", "Spa", "Restaurant", "Beach Access"],
  },
];
